name: Deploy Backend to VPS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        continue-on-error: false

      - name: Run linter
        run: npm run lint
        continue-on-error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            echo "Starting deployment..."
            
            # Navigate to app directory
            cd ${{ secrets.APP_PATH }}
            
            # Pull latest changes
            git pull origin main
            
            # Install dependencies
            npm ci --production
            
            # Restart PM2 process
            pm2 restart ${{ secrets.PM2_APP_NAME }} || pm2 start ecosystem.config.js
            
            # Save PM2 configuration
            pm2 save
            
            echo "Deployment completed successfully!"
          EOF

      - name: Health Check
        run: |
          sleep 30
          curl -f https://serverdevops.khoipn.id.vn/health || curl -f https://serverdevops.khoipn.id.vn/ || exit 1
