name: Deploy Backend to VPS

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_PORT: ${{ secrets.VPS_PORT || '22' }}
          APP_PATH: ${{ secrets.APP_PATH }}
          PORT: ${{ secrets.PORT || '3000' }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: $VPS_HOST
          username: $VPS_USER
          key: $VPS_SSH_KEY
          port: 22
          script: |
            set -e
            echo "🚀 Starting backend deployment..."

            # Navigate to app directory
            cd $APP_PATH

            # Create environment file
            cat > .env << 'EOF'
            PORT=$PORT
            MONGODB_URI=$MONGODB_URI
            EOF

            # Set proper permissions
            chmod 600 .env

            # Pull latest changes
            git pull origin main

            # Install dependencies
            npm ci --production

            # Run database migrations if they exist
            if [ -f "migrate.js" ]; then
              npm run migrate
            fi

            # Restart PM2 process
            pm2 restart $PM2_APP_NAME || pm2 start ecosystem.config.js

            # Save PM2 configuration
            pm2 save

            echo "✅ Backend deployment completed successfully!"

      - name: Health Check
        run: |
          sleep 30
          curl -f https://serverdevops.khoipn.id.vn/health || curl -f https://serverdevops.khoipn.id.vn/ || exit 1
